import { extractBalancedJson } from '../../../server_pure_helpers.js';
import { shouldExpandMealAgent } from '../../mealBuild/shouldExpandMealAgent.js';
import { t, interpolate } from '../../utils/i18n.js';
import { foodAnalyzeSchema } from './server_food_analyze_schema.js';

/**
 * F-8.10 shard 4 — dietitian dispatch seams, extracted verbatim from
 * runFoodAnalyze. Pure input→output units; streaming/LLM calls stay inline.
 */

/** LLM-output JSON repair: balanced-extract + runaway-decimal + foodType trims. */
export function sanitizeLlmJsonOutput(textOutput: string): {
  cleanJson: string;
  extractedScratchpad: string;
} {
  let cleanJson = extractBalancedJson(textOutput);
  const extractedScratchpad = textOutput.replace(cleanJson, "").replace(/```(?:json)?/gi, "").trim();
  // Sanitize pathological weightGrams values like "350.000000...000" → "350"
  // These are generated by the LLM and inflate JSON size causing truncation errors
  cleanJson = cleanJson.replace(/"(\d+)\.0{10,}(\d*)"/g, (_, int, tail) => `"${int}${tail ? '.' + tail.replace(/0+$/, '') : ''}"`);
  cleanJson = cleanJson.replace(/:\s*(\d+)\.0{10,}\d*/g, (_, int) => `: ${int}`);
  // Robust fallback for any unquoted or quoted decimal with long runaway zeros (e.g. 150.00000000000003g)
  cleanJson = cleanJson.replace(/(\d+)\.(\d*?)0{10,}(\d*)/g, (match, intPart, midPart, endPart) => {
    const combinedFrac = (midPart + endPart).replace(/0+$/, '');
    return combinedFrac ? `${intPart}.${combinedFrac}` : intPart;
  });
  // Sanitize runaway/repeating string values in fields like foodType
  cleanJson = cleanJson.replace(/"foodType"\s*:\s*"([^"]{80,})"/g, (_, val) => {
    const firstToken = val.split(/[\s,]+/)[0] || 'protein';
    return `"foodType": "${firstToken}"`;
  });
  return { cleanJson, extractedScratchpad };
}

export interface DietitianSkipArgs {
  isPureWeightModification: boolean;
  activeMeal: any;
  userSelectedMode?: string;
  weightRefineIntent: { isRefine?: boolean; weightGrams?: number; targetHint?: string; kind?: string };
  message?: string;
  isModifySession: boolean;
  hasActiveMealDocument: boolean;
  visionScoutRanAndReturnedItems: boolean;
  preCalculatedItems: any;
  visionScoutItems: any;
  imagePayloads: any;
  visionScoutContentType?: string;
  rawScoutData: any;
}

/** F-10 adaptive skip gates: pure-scale refine and single-agent create. */
export function computeDietitianSkipGates(args: DietitianSkipArgs): {
  canSkipDietitianForPureScale: boolean;
  isCreateSession: boolean;
  hasBarcode: boolean;
  hasReceipt: boolean;
  canSkipDietitianForCreate: boolean;
} {
  const {
    isPureWeightModification,
    activeMeal,
    userSelectedMode,
    weightRefineIntent,
    message,
    isModifySession,
    hasActiveMealDocument,
    visionScoutRanAndReturnedItems,
    preCalculatedItems,
    visionScoutItems,
    imagePayloads,
    visionScoutContentType,
    rawScoutData,
  } = args;
  const canSkipDietitianForPureScale = Boolean(
    isPureWeightModification &&
    activeMeal &&
    userSelectedMode !== 'compare' &&
    weightRefineIntent.isRefine &&
    typeof weightRefineIntent.weightGrams === 'number' &&
    weightRefineIntent.weightGrams > 0 &&
    !weightRefineIntent.targetHint &&
    (weightRefineIntent.kind === 'absolute_grams' || weightRefineIntent.kind === 'whole_pack') &&
    (!Array.isArray(activeMeal.itemsBreakdown) || activeMeal.itemsBreakdown.length <= 1) &&
    !/\b(only|remove|delete|without|except|no|instead|replace|add|plus|with|not|didn't|did\s+not)\b/i.test(message || '')
  );
  const isCreateSession = !isModifySession && !hasActiveMealDocument && userSelectedMode !== 'compare' && userSelectedMode !== 'discussion';
  const hasBarcode = Boolean(visionScoutItems?.some((it: any) => it.barcode || /^\d{6,}$/.test(it.keyword || '')));
  const hasReceipt = Boolean(
    visionScoutContentType === 'menu_or_poster' ||
    visionScoutContentType === 'receipt' ||
    rawScoutData?.receiptTable ||
    visionScoutItems?.some((it: any) => it.source === 'receipt')
  );
  const canSkipDietitianForCreate = Boolean(
    isCreateSession &&
    visionScoutRanAndReturnedItems &&
    Array.isArray(preCalculatedItems) &&
    preCalculatedItems.length > 0 &&
    !shouldExpandMealAgent({
      dishCount: visionScoutItems.length,
      imageCount: imagePayloads?.length || 0,
      hasReceipt,
      hasBarcode,
    })
  );
  return { canSkipDietitianForPureScale, isCreateSession, hasBarcode, hasReceipt, canSkipDietitianForCreate };
}

export interface ScoutTotals {
  totalSugar: number;
  totalSatFat: number;
  totalP: number;
}

/**
 * F-8.10 shard 15 — single-agent-create verdict ladder, extracted verbatim
 * from runFoodAnalyze. Existing scout verdicts pass through untouched.
 */
export function decideScoutVerdict(args: {
  scoutVerdict: any;
  totals: ScoutTotals;
  mealName?: string;
  language?: unknown;
}): any {
  const { totals, mealName, language } = args;
  let scoutVerdict = args.scoutVerdict;
  if (!scoutVerdict || typeof scoutVerdict !== 'object' || !scoutVerdict.label) {
    if (totals.totalSugar >= 30) {
      scoutVerdict = { label: t(language, 'verdictHighGlycemicSugar'), level: 'warning' };
    } else if (totals.totalSatFat >= 15) {
      scoutVerdict = { label: t(language, 'verdictElevatedSatFat'), level: 'warning' };
    } else if (totals.totalP >= 25) {
      scoutVerdict = { label: t(language, 'verdictLeanMuscle'), level: 'good' };
    } else if (/probiotic|fermented|yogurt|kefir|yakult/i.test(mealName || '')) {
      scoutVerdict = { label: t(language, 'verdictGutMicrobiome'), level: totals.totalSugar >= 25 ? 'neutral' : 'good' };
    } else {
      scoutVerdict = { label: t(language, 'verdictSupportsMetabolicEnergy'), level: 'neutral' };
    }
  }
  return scoutVerdict;
}

/**
 * F-8.10 shard 15 — single-agent-create advice ladder, extracted verbatim
 * from runFoodAnalyze. Existing scout advice passes through untouched.
 */
export function decideScoutAdvice(args: {
  rawAdvice: any;
  totals: ScoutTotals;
  mealName?: string;
  language?: unknown;
}): string {
  const { totals, mealName, language } = args;
  let rawAdvice = args.rawAdvice;
  if (!rawAdvice || String(rawAdvice).trim().length === 0) {
    if (/probiotic|yakult|kefir|yogurt/i.test(mealName || '')) {
      rawAdvice = t(language, 'adviceProbioticSugar').replace('{grams}', String(Math.round(totals.totalSugar)));
    } else if (totals.totalP >= 20) {
      rawAdvice = t(language, 'adviceSolidProtein').replace('{grams}', String(Math.round(totals.totalP)));
    } else if (totals.totalSugar >= 30) {
      rawAdvice = t(language, 'adviceHighSugar').replace('{grams}', String(Math.round(totals.totalSugar)));
    } else {
      rawAdvice = t(language, 'adviceLoggedBalanced').replace('{name}', String(mealName));
    }
  }
  return rawAdvice;
}

export interface DietitianCallArgs {
  engine: any;
  finalSystemInstruction: string;
  promptText: string;
}

/**
 * F-8.10 shard 17 — dietitian LLM call args, extracted verbatim from
 * runFoodAnalyze. Images are stripped: the coach consumes the structured
 * JSON nutrition summary. Schema responses are non-thinking so output
 * streams instead of batching.
 */
export function buildDietitianCallArgs(args: DietitianCallArgs): Record<string, any> {
  const { engine, finalSystemInstruction, promptText } = args;
  return {
    modelId: (typeof engine === 'object' ? engine?.name || engine?.model : engine) || "gemini-3.5-flash-lite", // Updating to flash-lite as recommended
    systemInstruction: finalSystemInstruction,
    promptText,
    imagePayloads: undefined, // Strip redundant image payloads: Dietitian Coach consumes structured JSON nutrition summary
    responseMimeType: "application/json" as const,
    responseSchema: foodAnalyzeSchema,
    maxOutputTokens: 8192, // Boosted to ensure all items fit
    skipThinking: true, // Scout already sets this; dietitian's schema also puts
    logStagePrefix: 'dietitian',
    // _internalReasoning first, which is where the live _internalReasoning text actually
    // comes from — so this does not remove the _internalReasoning. It removes the
    // separate native-thinking output stream, which combined with responseSchema
    // was suspected of causing the model to batch output instead of streaming it.
  };
}

/**
 * F-8.10 shard 18 — skip-path builders, extracted verbatim from runFoodAnalyze.
 */

/** Pure-scale refine response: label-locked meal scaled without an LLM call. */
export function buildPureScaleResponse(args: { targetWeightGrams: number; language?: unknown }): {
  textOutput: string;
  rawParsed: any;
} {
  const { targetWeightGrams: targetWeight, language } = args;
  const textOutput = JSON.stringify({
    _internalReasoning: `[Refine] scale-only: Scaled meal directly to ${targetWeight}g`,
    verdict: { label: t(language, 'verdictPortionControl'), level: "neutral" },
    message: interpolate(t(language, 'messageScaledPortion'), { grams: targetWeight }),
    mode: "modify",
    modificationCommand: [
      {
        action: "update_weight",
        itemName: "total",
        newWeightGrams: targetWeight
      }
    ]
  });
  return { textOutput, rawParsed: JSON.parse(textOutput) };
}

/** Sums precalc ledgers into create-path totals. */
export function sumPrecalcTotals(preCalculatedItems: any): {
  totalGrams: number;
  totalCals: number;
  totalP: number;
  totalC: number;
  totalF: number;
  totalSugar: number;
  totalAddedSugar: number;
  totalSatFat: number;
} {
  return {
    totalGrams: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.estimatedWeightGrams) || 0), 0),
    totalCals: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.calories) || 0), 0),
    totalP: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.protein) || 0), 0),
    totalC: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.carbohydrates) || 0), 0),
    totalF: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.totalFat) || 0), 0),
    totalSugar: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.sugar ?? it.nutrients?.totalSugar ?? it.nutrients?.addedSugar) || 0), 0),
    totalAddedSugar: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.addedSugar) || 0), 0),
    totalSatFat: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.saturatedFat) || 0), 0),
  };
}

/** Dietitian retry backoff: 503/429/UNAVAILABLE waits longer. */
export function computeDietitianRetryDelay(lastDietitianErr: any): number {
  return lastDietitianErr?.message?.includes('503') || lastDietitianErr?.message?.includes('429') || lastDietitianErr?.message?.includes('UNAVAILABLE') ? 3000 : 1000;
}
