import { extractBalancedJson } from '../../../server_pure_helpers.js';
import { shouldExpandMealAgent } from '../../mealBuild/shouldExpandMealAgent.js';
import { t, interpolate } from '../../utils/i18n.js';
import { NUTRIENT_KEYS } from '../../utils/nutrients.js';
import { reconcileMessageWithLedger } from '../../mealBuild/narration.js';
import { asyncParseLLMJSON, validateOrFallback, RouteAgentSchema } from '../../../server.js';
import { foodAnalyzeSchema } from './server_food_analyze_schema.js';

/**
 * F-8.10 shard 4 — dietitian dispatch seams, extracted verbatim from
 * runFoodAnalyze. Pure input→output units; streaming/LLM calls stay inline.
 */

/** LLM-output JSON repair: balanced-extract + runaway-decimal + foodType trims. */
export function sanitizeLlmJsonOutput(textOutput: string): {
  cleanJson: string;
  extractedScratchpad: string;
} {
  let cleanJson = extractBalancedJson(textOutput);
  const extractedScratchpad = textOutput.replace(cleanJson, "").replace(/```(?:json)?/gi, "").trim();
  // Sanitize pathological weightGrams values like "350.000000...000" → "350"
  // These are generated by the LLM and inflate JSON size causing truncation errors
  cleanJson = cleanJson.replace(/"(\d+)\.0{10,}(\d*)"/g, (_, int, tail) => `"${int}${tail ? '.' + tail.replace(/0+$/, '') : ''}"`);
  cleanJson = cleanJson.replace(/:\s*(\d+)\.0{10,}\d*/g, (_, int) => `: ${int}`);
  // Robust fallback for any unquoted or quoted decimal with long runaway zeros (e.g. 150.00000000000003g)
  cleanJson = cleanJson.replace(/(\d+)\.(\d*?)0{10,}(\d*)/g, (match, intPart, midPart, endPart) => {
    const combinedFrac = (midPart + endPart).replace(/0+$/, '');
    return combinedFrac ? `${intPart}.${combinedFrac}` : intPart;
  });
  // Sanitize runaway/repeating string values in fields like foodType
  cleanJson = cleanJson.replace(/"foodType"\s*:\s*"([^"]{80,})"/g, (_, val) => {
    const firstToken = val.split(/[\s,]+/)[0] || 'protein';
    return `"foodType": "${firstToken}"`;
  });
  return { cleanJson, extractedScratchpad };
}

export interface DietitianSkipArgs {
  isPureWeightModification: boolean;
  activeMeal: any;
  userSelectedMode?: string;
  weightRefineIntent: { isRefine?: boolean; weightGrams?: number; targetHint?: string; kind?: string };
  message?: string;
  isModifySession: boolean;
  hasActiveMealDocument: boolean;
  visionScoutRanAndReturnedItems: boolean;
  preCalculatedItems: any;
  visionScoutItems: any;
  imagePayloads: any;
  visionScoutContentType?: string;
  rawScoutData: any;
}

/** F-10 adaptive skip gates: pure-scale refine and single-agent create. */
export function computeDietitianSkipGates(args: DietitianSkipArgs): {
  canSkipDietitianForPureScale: boolean;
  isCreateSession: boolean;
  hasBarcode: boolean;
  hasReceipt: boolean;
  canSkipDietitianForCreate: boolean;
} {
  const {
    isPureWeightModification,
    activeMeal,
    userSelectedMode,
    weightRefineIntent,
    message,
    isModifySession,
    hasActiveMealDocument,
    visionScoutRanAndReturnedItems,
    preCalculatedItems,
    visionScoutItems,
    imagePayloads,
    visionScoutContentType,
    rawScoutData,
  } = args;
  const canSkipDietitianForPureScale = Boolean(
    isPureWeightModification &&
    activeMeal &&
    userSelectedMode !== 'compare' &&
    weightRefineIntent.isRefine &&
    typeof weightRefineIntent.weightGrams === 'number' &&
    weightRefineIntent.weightGrams > 0 &&
    !weightRefineIntent.targetHint &&
    (weightRefineIntent.kind === 'absolute_grams' || weightRefineIntent.kind === 'whole_pack') &&
    (!Array.isArray(activeMeal.itemsBreakdown) || activeMeal.itemsBreakdown.length <= 1) &&
    !/\b(only|remove|delete|without|except|no|instead|replace|add|plus|with|not|didn't|did\s+not)\b/i.test(message || '')
  );
  const isCreateSession = !isModifySession && !hasActiveMealDocument && userSelectedMode !== 'compare' && userSelectedMode !== 'discussion';
  const hasBarcode = Boolean(visionScoutItems?.some((it: any) => it.barcode || /^\d{6,}$/.test(it.keyword || '')));
  const hasReceipt = Boolean(
    visionScoutContentType === 'menu_or_poster' ||
    visionScoutContentType === 'receipt' ||
    rawScoutData?.receiptTable ||
    visionScoutItems?.some((it: any) => it.source === 'receipt')
  );
  const canSkipDietitianForCreate = Boolean(
    isCreateSession &&
    visionScoutRanAndReturnedItems &&
    Array.isArray(preCalculatedItems) &&
    preCalculatedItems.length > 0 &&
    !shouldExpandMealAgent({
      dishCount: visionScoutItems.length,
      imageCount: imagePayloads?.length || 0,
      hasReceipt,
      hasBarcode,
    })
  );
  return { canSkipDietitianForPureScale, isCreateSession, hasBarcode, hasReceipt, canSkipDietitianForCreate };
}

export interface ScoutTotals {
  totalSugar: number;
  totalSatFat: number;
  totalP: number;
}

/**
 * F-8.10 shard 15 — single-agent-create verdict ladder, extracted verbatim
 * from runFoodAnalyze. Existing scout verdicts pass through untouched.
 */
export function decideScoutVerdict(args: {
  scoutVerdict: any;
  totals: ScoutTotals;
  mealName?: string;
  language?: unknown;
}): any {
  const { totals, mealName, language } = args;
  let scoutVerdict = args.scoutVerdict;
  if (!scoutVerdict || typeof scoutVerdict !== 'object' || !scoutVerdict.label) {
    if (totals.totalSugar >= 30) {
      scoutVerdict = { label: t(language, 'verdictHighGlycemicSugar'), level: 'warning' };
    } else if (totals.totalSatFat >= 15) {
      scoutVerdict = { label: t(language, 'verdictElevatedSatFat'), level: 'warning' };
    } else if (totals.totalP >= 25) {
      scoutVerdict = { label: t(language, 'verdictLeanMuscle'), level: 'good' };
    } else if (/probiotic|fermented|yogurt|kefir|yakult/i.test(mealName || '')) {
      scoutVerdict = { label: t(language, 'verdictGutMicrobiome'), level: totals.totalSugar >= 25 ? 'neutral' : 'good' };
    } else {
      scoutVerdict = { label: t(language, 'verdictSupportsMetabolicEnergy'), level: 'neutral' };
    }
  }
  return scoutVerdict;
}

/**
 * F-8.10 shard 15 — single-agent-create advice ladder, extracted verbatim
 * from runFoodAnalyze. Existing scout advice passes through untouched.
 */
export function decideScoutAdvice(args: {
  rawAdvice: any;
  totals: ScoutTotals;
  mealName?: string;
  language?: unknown;
}): string {
  const { totals, mealName, language } = args;
  let rawAdvice = args.rawAdvice;
  if (!rawAdvice || String(rawAdvice).trim().length === 0) {
    if (/probiotic|yakult|kefir|yogurt/i.test(mealName || '')) {
      rawAdvice = t(language, 'adviceProbioticSugar').replace('{grams}', String(Math.round(totals.totalSugar)));
    } else if (totals.totalP >= 20) {
      rawAdvice = t(language, 'adviceSolidProtein').replace('{grams}', String(Math.round(totals.totalP)));
    } else if (totals.totalSugar >= 30) {
      rawAdvice = t(language, 'adviceHighSugar').replace('{grams}', String(Math.round(totals.totalSugar)));
    } else {
      rawAdvice = t(language, 'adviceLoggedBalanced').replace('{name}', String(mealName));
    }
  }
  return rawAdvice;
}

export interface DietitianCallArgs {
  engine: any;
  finalSystemInstruction: string;
  promptText: string;
}

/**
 * F-8.10 shard 17 — dietitian LLM call args, extracted verbatim from
 * runFoodAnalyze. Images are stripped: the coach consumes the structured
 * JSON nutrition summary. Schema responses are non-thinking so output
 * streams instead of batching.
 */
export function buildDietitianCallArgs(args: DietitianCallArgs): Record<string, any> {
  const { engine, finalSystemInstruction, promptText } = args;
  return {
    modelId: (typeof engine === 'object' ? engine?.name || engine?.model : engine) || "gemini-3.5-flash-lite", // Updating to flash-lite as recommended
    systemInstruction: finalSystemInstruction,
    promptText,
    imagePayloads: undefined, // Strip redundant image payloads: Dietitian Coach consumes structured JSON nutrition summary
    responseMimeType: "application/json" as const,
    responseSchema: foodAnalyzeSchema,
    maxOutputTokens: 8192, // Boosted to ensure all items fit
    skipThinking: true, // Scout already sets this; dietitian's schema also puts
    logStagePrefix: 'dietitian',
    // _internalReasoning first, which is where the live _internalReasoning text actually
    // comes from — so this does not remove the _internalReasoning. It removes the
    // separate native-thinking output stream, which combined with responseSchema
    // was suspected of causing the model to batch output instead of streaming it.
  };
}

/**
 * F-8.10 shard 18 — skip-path builders, extracted verbatim from runFoodAnalyze.
 */

/** Pure-scale refine response: label-locked meal scaled without an LLM call. */
export function buildPureScaleResponse(args: { targetWeightGrams: number; language?: unknown }): {
  textOutput: string;
  rawParsed: any;
} {
  const { targetWeightGrams: targetWeight, language } = args;
  const textOutput = JSON.stringify({
    _internalReasoning: `[Refine] scale-only: Scaled meal directly to ${targetWeight}g`,
    verdict: { label: t(language, 'verdictPortionControl'), level: "neutral" },
    message: interpolate(t(language, 'messageScaledPortion'), { grams: targetWeight }),
    mode: "modify",
    modificationCommand: [
      {
        action: "update_weight",
        itemName: "total",
        newWeightGrams: targetWeight
      }
    ]
  });
  return { textOutput, rawParsed: JSON.parse(textOutput) };
}

/** Sums precalc ledgers into create-path totals. */
export function sumPrecalcTotals(preCalculatedItems: any): {
  totalGrams: number;
  totalCals: number;
  totalP: number;
  totalC: number;
  totalF: number;
  totalSugar: number;
  totalAddedSugar: number;
  totalSatFat: number;
} {
  return {
    totalGrams: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.estimatedWeightGrams) || 0), 0),
    totalCals: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.calories) || 0), 0),
    totalP: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.protein) || 0), 0),
    totalC: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.carbohydrates) || 0), 0),
    totalF: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.totalFat) || 0), 0),
    totalSugar: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.sugar ?? it.nutrients?.totalSugar ?? it.nutrients?.addedSugar) || 0), 0),
    totalAddedSugar: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.addedSugar) || 0), 0),
    totalSatFat: preCalculatedItems.reduce((sum: number, it: any) => sum + (Number(it.nutrients?.saturatedFat) || 0), 0),
  };
}

/** Dietitian retry backoff: 503/429/UNAVAILABLE waits longer. */
export function computeDietitianRetryDelay(lastDietitianErr: any): number {
  return lastDietitianErr?.message?.includes('503') || lastDietitianErr?.message?.includes('429') || lastDietitianErr?.message?.includes('UNAVAILABLE') ? 3000 : 1000;
}

/**
 * F-8.10 shard 19 — truncation repair fallback, extracted verbatim from
 * runFoodAnalyze. Rebalances quotes/brackets on truncated LLM JSON.
 * Throws the ORIGINAL parse error when repair also fails.
 */
export function repairTruncatedJson(args: {
  cleanJson: string;
  extractedScratchpad: string;
  parseErr: any;
  onLog: (msg: string) => void;
}): any {
  const { cleanJson, extractedScratchpad, parseErr, onLog } = args;
  let repaired = cleanJson.trim();
  // 1. Remove trailing comma followed by a half-written key
  repaired = repaired.replace(/,\s*"[^"]*"?\s*$/, "");
  // 2. Handle unescaped double quotes inside an unclosed string
  let quoteCount = 0;
  for (let idx = 0; idx < repaired.length; idx++) {
    if (repaired[idx] === '"' && (idx === 0 || repaired[idx - 1] !== '\\')) {
      quoteCount++;
    }
  }
  if (quoteCount % 2 !== 0) {
    repaired += '"';
  }
  // 3. Remove trailing comma or colon
  if (repaired.endsWith(",")) {
    repaired = repaired.slice(0, -1).trim();
  } else if (repaired.endsWith(":")) {
    repaired += "null";
  }
  // 4. Count open braces and brackets outside strings
  let openBraces = 0;
  let openBrackets = 0;
  let insideStr = false;
  for (let i = 0; i < repaired.length; i++) {
    const char = repaired[i];
    if (char === '"' && (i === 0 || repaired[i - 1] !== '\\')) {
      insideStr = !insideStr;
    }
    if (!insideStr) {
      if (char === '{') openBraces++;
      else if (char === '}') openBraces--;
      else if (char === '[') openBrackets++;
      else if (char === ']') openBrackets--;
    }
  }
  repaired += ']'.repeat(Math.max(0, openBrackets)) + '}'.repeat(Math.max(0, openBraces));
  try {
    const rawParsed = JSON.parse(repaired);
    if (!rawParsed._internalReasoning && extractedScratchpad) {
      rawParsed._internalReasoning = extractedScratchpad;
    }
    onLog(`[JSON Parse Error] Robust truncation repair succeeded.`);
    return rawParsed;
  } catch (repairErr: any) {
    onLog(`[JSON Parse Error] Robust truncation repair also failed: ${repairErr.message}.`);
    throw parseErr;
  }
}

export interface DensityCheckArgs {
  preCalculatedItems: any[];
  aggregatedNutrients: any;
  beveragePattern: RegExp;
  onLog: (msg: string) => void;
}

/**
 * F-8.10 shard 19 — pre-dietitian density check, extracted verbatim from
 * runFoodAnalyze. Rescales implausible beverage calories and rolls up
 * aggregated nutrients. Mutates items in place, as inline.
 */
export function applyPreDietitianDensityCheck(args: DensityCheckArgs): Record<string, number> {
  const { preCalculatedItems, aggregatedNutrients: incoming, beveragePattern, onLog } = args;
  let aggregatedNutrients = incoming;
  if (Array.isArray(preCalculatedItems)) {
    preCalculatedItems.forEach((it: any) => {
      if (!it || !it.weightGrams || !it.nutrients) return;
      const cals = Number(it.nutrients.calories || 0);
      const nameLower = String(it.name || it.keyword || '').toLowerCase();
      const isBeverage = beveragePattern.test(nameLower) || nameLower.includes('latte') || nameLower.includes('coffee') || nameLower.includes('drink');
      if (isBeverage && it.weightGrams >= 150 && cals > 600) {
        const maxAllowedCals = Math.round((it.weightGrams / 100) * 110);
        const factor = maxAllowedCals / cals;
        onLog(`[Pre-Dietitian Reality Check] Rescaling beverage item "${it.name}" from ${cals} kcal -> ${maxAllowedCals} kcal prior to Dietitian prompt payload.`);
        NUTRIENT_KEYS.forEach(k => {
          if (it.nutrients[k] != null && typeof it.nutrients[k] === 'number') {
            it.nutrients[k] = Math.round(it.nutrients[k] * factor * 10) / 10;
          }
        });
      }
    });
    if (preCalculatedItems.length > 0) {
      if (!aggregatedNutrients || typeof aggregatedNutrients !== 'object') {
        aggregatedNutrients = {};
      }
      NUTRIENT_KEYS.forEach(k => {
        const sum = preCalculatedItems.reduce((acc: number, item: any) => acc + (Number(item?.nutrients?.[k]) || 0), 0);
        aggregatedNutrients[k] = Math.round(sum * 10) / 10;
      });
    }
  }
  return aggregatedNutrients;
}

export interface DietitianParseArgs {
  cleanJson: string;
  extractedScratchpad: string;
  language?: unknown;
}

/**
 * F-8.10 shard 25 — dietitian parse + validate, extracted verbatim from
 * runFoodAnalyze. Falls back to a neutral analyzed-log shell on schema
 * mismatch; throws on unparseable JSON (caller repairs).
 */
export async function parseAndValidateDietitian(args: DietitianParseArgs): Promise<any> {
  const { cleanJson, extractedScratchpad, language } = args;
  let rawParsed = await asyncParseLLMJSON(cleanJson);
  rawParsed = validateOrFallback(RouteAgentSchema, rawParsed, cleanJson, "RouteAgent", {
    _internalReasoning: "",
    verdict: { label: t(language, 'verdictSupportsMetabolicEnergy'), level: "neutral" },
    message: t(language, 'fallbackAnalyzedLog'),
    foodData: { date: new Date().toISOString().split('T')[0], name: "Meal", itemsBreakdown: [] }
  });
  if (!rawParsed._internalReasoning && extractedScratchpad) {
    rawParsed._internalReasoning = extractedScratchpad;
  }
  return rawParsed;
}

export interface CreateSkipSynthesisArgs {
  rawScoutData: any;
  visionScoutItems: any[];
  preCalculatedItems: any[];
  totals: {
    totalGrams: number; totalCals: number; totalP: number; totalC: number;
    totalF: number; totalSugar: number; totalAddedSugar: number; totalSatFat: number;
  };
  scoutVerdict: any;
  rawAdvice: string;
  scoutConfidenceRating?: string;
  scoutConfidenceComment?: string;
  scoutCookingMethod?: string;
  scoutInternalReasoning?: string | null;
  diningEnvironment?: string;
  language?: unknown;
}

/**
 * F-8.10 shard 28 — single-agent-create synthesis, extracted verbatim from
 * runFoodAnalyze. Reconciles the message with the ledger and serializes
 * the dietitian-shaped response (which the caller re-parses, as inline).
 */
export function buildCreateSkipResponse(args: CreateSkipSynthesisArgs): {
  textOutput: string;
  rawParsed: any;
} {
  const {
    rawScoutData, visionScoutItems, preCalculatedItems, totals, scoutVerdict, rawAdvice,
    scoutConfidenceRating, scoutConfidenceComment, scoutCookingMethod,
    scoutInternalReasoning, diningEnvironment, language,
  } = args;
  const { totalGrams, totalCals, totalP, totalC, totalF } = totals;
  const mealName = rawScoutData?.mealName || rawScoutData?.name || (visionScoutItems.length === 1 ? (visionScoutItems[0].originalName || visionScoutItems[0].keyword) : t(language, 'balancedMealFallbackName'));
  const formattedMsg = reconcileMessageWithLedger(rawAdvice, {
    mealName,
    weightGrams: totalGrams,
    calories: Math.round(totalCals),
    protein: Math.round(totalP * 10) / 10,
    carbohydrates: Math.round(totalC * 10) / 10,
    totalFat: Math.round(totalF * 10) / 10,
  }, language);
  // preCalculatedItems is captured from the caller scope via totals source
  const textOutput = JSON.stringify({
    _internalReasoning: scoutInternalReasoning || '[MealAgent] Single-agent create path',
    mode: 'new_log',
    message: formattedMsg,
    verdict: scoutVerdict,
    foodData: {
      name: mealName,
      weightGrams: String(totalGrams),
      cookingMethod: scoutCookingMethod || t(language, 'cookingMethodUnknown'),
      scoutConfidenceRating: scoutConfidenceRating || 'High (>90%)',
      scoutConfidenceComment: scoutConfidenceComment || '',
      diningEnvironment: diningEnvironment || 'unknown',
      itemsBreakdown: preCalculatedItems.map((p: any) => ({
        canonicalDbName: p.keyword || p.originalName,
        originalName: p.originalName,
        weightGrams: String(p.estimatedWeightGrams),
        dbSource: p.dbSource || 'estimated',
        dbId: p.dbId || null,
        foodType: p.foodType || 'composed',
        rawNutritionLabel: p.rawNutritionLabel || null,
        labelNutrientsPerServing: p.labelNutrientsPerServing || null,
      }))
    }
  });
  return { textOutput, rawParsed: JSON.parse(textOutput) };
}

/**
 * F-8.10 shard 28 — salvaged aggregates, extracted verbatim from
 * runFoodAnalyze. Zero-fills and sums the 31 keys over precalc items.
 */
export function sumSalvagedAggregates(preCalculatedItems: any): Record<string, number> {
  const salvagedAggregatedNutrients: Record<string, number> = {};
  NUTRIENT_KEYS.forEach(k => salvagedAggregatedNutrients[k] = 0);
  if (preCalculatedItems && Array.isArray(preCalculatedItems)) {
    preCalculatedItems.forEach((p: any) => {
      if (p.nutrients) {
        NUTRIENT_KEYS.forEach(k => {
          salvagedAggregatedNutrients[k] = parseFloat(((salvagedAggregatedNutrients[k] || 0) + (Number(p.nutrients[k]) || 0)).toFixed(2));
        });
      }
    });
  }
  return salvagedAggregatedNutrients;
}

export interface DietitianDispatchArgs {
  callArgs: any;
  callUnifiedLLM: (args: any) => Promise<any>;
  language?: unknown;
  onLog: (msg: string) => void;
  onStreamChunk?: (chunk: string, isThought?: boolean) => void;
}

/**
 * F-8.10 shard 30 — single dietitian attempt, extracted verbatim from
 * runFoodAnalyze. Streams via the injected hook, then sanitizes, parses,
 * validates, and repairs. Throws on unparseable JSON (caller retries).
 */
export async function runDietitianDispatch(args: DietitianDispatchArgs): Promise<{
  textOutput: string;
  rawParsed: any;
}> {
  const { callArgs, callUnifiedLLM, language, onLog, onStreamChunk } = args;
  if (onStreamChunk) {
    callArgs.onStream = (chunk: string, isThought?: boolean) => onStreamChunk(chunk, isThought);
  }
  const textOutput = await callUnifiedLLM(callArgs);
  const { cleanJson, extractedScratchpad } = sanitizeLlmJsonOutput(textOutput);
  let rawParsed;
  try {
    rawParsed = await parseAndValidateDietitian({ cleanJson, extractedScratchpad, language });
  } catch (parseErr: any) {
    onLog(`[JSON Parse Error] JSON parse failed: ${parseErr.message}. Attempting robust truncation repair...`);
    rawParsed = repairTruncatedJson({ cleanJson, extractedScratchpad, parseErr, onLog });
  }
  return { textOutput, rawParsed };
}

export interface DietitianRetryArgs {
  llmCallArgs: any;
  callUnifiedLLM: (args: any) => Promise<any>;
  language?: unknown;
  maxAttempts?: number;
  onStreamChunk?: (chunk: string, isThought?: boolean) => void;
  sleep: (ms: number) => Promise<void>;
  onLog: (msg: string) => void;
}

/**
 * F-8.10 shard 30 — dietitian retry loop, extracted verbatim from
 * runFoodAnalyze. Abort/timeout errors throw immediately; other failures
 * retry with backoff. Returns empty textOutput when attempts exhaust.
 */
export async function runDietitianRetryLoop(args: DietitianRetryArgs): Promise<{
  textOutput: string;
  rawParsed: any;
}> {
  const {
    llmCallArgs, callUnifiedLLM, language, maxAttempts = 3, onStreamChunk, sleep, onLog,
  } = args;
  let textOutput: string = "";
  let rawParsed: any;
  let attempts = 0;
  let lastDietitianErr: any = null;
  while (attempts < maxAttempts) {
    attempts++;
    try {
      if (attempts > 1) {
        const delay = computeDietitianRetryDelay(lastDietitianErr);
        onLog(`[Dietitian] Waiting ${delay}ms before retry...`);
        await sleep(delay);
        onLog(`[Dietitian] Retrying LLM call (Attempt ${attempts} of ${maxAttempts})...`);
      }
      const result = await runDietitianDispatch({ callArgs: llmCallArgs, callUnifiedLLM, language, onLog, onStreamChunk });
      textOutput = result.textOutput;
      rawParsed = result.rawParsed;
      break;
    } catch (err: any) {
      lastDietitianErr = err;
      const isAbort = err.name === 'AbortError' || (err.message && err.message.toLowerCase().includes('abort'));
      if (isAbort) {
        onLog(`[Dietitian] Fatal error (Timeout) detected. Throwing immediately without retry.`);
        throw err;
      }
      onLog(`[Dietitian Attempt ${attempts} Failed] Error: ${err.message}`);
    }
  }
  if (!textOutput) {
    onLog(`[Dietitian Failed Permanently] All attempts failed. Last error: ${lastDietitianErr?.message}`);
    throw lastDietitianErr;
  }
  return { textOutput, rawParsed };
}
